image: docker:latest
services:
  - docker:dind

stages:
  - test
  - release

before_script:
  - apk --no-cache add git
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/${RELEASE_SCRIPTS_REPOSITORY}.git


variables:
  CONTAINER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH
  CONTAINER_IMAGE_PROD: $CI_REGISTRY/$CI_PROJECT_PATH/production
  DOCKER_DRIVER: overlay


test_dev:
  stage: test
  image: node:12-alpine
  environment:
    name: develop
  script:
    - sh ${RELEASE_SCRIPTS_DIRECTORY}/develop/test/before-script.sh
    - sh ${RELEASE_SCRIPTS_DIRECTORY}/develop/test/script.sh
  only:
    - develop


release_master:
  stage: release
  image: node:12-alpine
  environment:
    name: production
  script:
    - npm i -g typescript
    - sh ${RELEASE_SCRIPTS_DIRECTORY}/master/release/before-script.sh
    - sh ${RELEASE_SCRIPTS_DIRECTORY}/master/release/script.sh
  only:
    - master
